# Semantic Versioning Configuration
# This file defines how commit messages trigger version bumps

version:
  major:
    patterns:
      - "BREAKING CHANGE:"
      - "major:"
      - "!:"
  minor:
    patterns:
      - "feat:"
      - "feature:"
      - "minor:"
  patch:
    patterns:
      - "fix:"
      - "bugfix:"
      - "patch:"
      - "chore:"
      - "docs:"
      - "style:"
      - "refactor:"
      - "perf:"
      - "test:"

# Commit message format examples:
# feat: add new validation rule -> minor version bump
# fix: resolve null pointer exception -> patch version bump
# BREAKING CHANGE: remove deprecated API -> major version bump
# chore: update dependencies -> patch version bump
